roi:

  iam:

    clientSecret: qTDHzRP1LH9ABbKAPCZPdgqhpPs9CgZn

    urlServer: http://localhost:8080

    origin: http://localhost:8080

spring:

  security:

    oauth2:

      resourceserver:

        opaquetoken:

          introspection-uri: http://localhost:8080/realms/roiApex/protocol/openid-connect/token/introspect

          client-secret: ${roi.iam.clientSecret}

  datasource:

    url: jdbc:postgresql://localhost:5432/dev-roi-apex
